import {useEffect,useRef,useState} from "react";import {clampQuantity,mergeCatalogItem} from "./preorderHelpers.js";
export default function PreorderProductComposer({items,onChange,api}){const [query,setQuery]=useState(""),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[active,setActive]=useState(-1),[freeform,setFreeform]=useState("");const requestRef=useRef(null);const show=query.startsWith("@");
 useEffect(()=>{const term=query.replace(/^@/,"").trim();if(!show||term.length<2){setResults([]);setLoading(false);return undefined;}const timer=setTimeout(async()=>{requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;setLoading(true);try{const data=await api.suggestProducts(term,controller.signal);setResults(data.items||[]);setActive((data.items||[]).length?0:-1);}catch(error){if(error.name!=="AbortError")setResults([]);}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{clearTimeout(timer);requestRef.current?.abort();};},[query,show,api]);
 function choose(row){onChange(mergeCatalogItem(items,row));setQuery("");setResults([]);setActive(-1);}
 function keyDown(event){if(!show)return;if(event.key==="ArrowDown"){event.preventDefault();setActive(v=>Math.min(results.length-1,v+1));}else if(event.key==="ArrowUp"){event.preventDefault();setActive(v=>Math.max(0,v-1));}else if(event.key==="Enter"&&active>=0){event.preventDefault();choose(results[active]);}else if(event.key==="Escape"){setQuery("");setResults([]);}}
 function addFreeform(){const text=freeform.trim();if(!text)return;onChange([...items,{clientId:crypto.randomUUID(),itemKind:"FREEFORM",description:text,quantity:1}]);setFreeform("");setQuery("");}
 function quantity(id,delta){onChange(items.map(item=>item.clientId===id?{...item,quantity:clampQuantity(Number(item.quantity)+delta)}:item));}
 return <div className="preorder-composer"><label htmlFor="preorder-product-search">ค้นหาสินค้าในระบบ</label><div className="preorder-search-shell"><input id="preorder-product-search" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={keyDown} placeholder="พิมพ์ @ แล้วตามด้วยรหัส บาร์โค้ด หรือชื่อสินค้า" autoComplete="off" role="combobox" aria-expanded={show&&query.length>=3} aria-controls="preorder-suggestions" aria-activedescendant={active>=0?`preorder-option-${active}`:undefined}/>{show&&<div id="preorder-suggestions" className="preorder-suggestions" role="listbox">{query.replace(/^@/,"").trim().length<2?<p>พิมพ์อย่างน้อย 2 ตัวอักษร</p>:loading?<p>กำลังค้นหา…</p>:results.length?results.map((row,index)=><button type="button" id={`preorder-option-${index}`} role="option" aria-selected={active===index} className={active===index?"active":""} key={row.sku_id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(row)}><strong>{row.product_code} · {row.display_name}</strong><span>{[row.barcode,row.generic_name,row.unit].filter(Boolean).join(" · ")}</span></button>):<div className="preorder-no-match"><p>ไม่พบสินค้าที่ตรงกัน</p><label htmlFor="preorder-freeform">เขียนรายละเอียดสินค้านอกระบบ</label><textarea id="preorder-freeform" value={freeform} onChange={e=>setFreeform(e.target.value)} placeholder="ชื่อสินค้า ลักษณะ รุ่น ขนาด หรือข้อมูลบนฉลาก"/><button type="button" onClick={addFreeform} disabled={!freeform.trim()}>เพิ่มสินค้านอกระบบ</button></div>}</div>}</div>{items.length>0&&<div className="preorder-selected-items">{items.map(item=><article key={item.clientId}><div><strong>{item.itemKind==="CATALOG"?item.displayName:"สินค้านอกระบบ"}</strong><p>{item.itemKind==="CATALOG"?[item.productCode,item.barcode,item.unit].filter(Boolean).join(" · "):item.description}</p></div><div className="preorder-qty" aria-label="จำนวนสินค้า"><button type="button" aria-label="ลดจำนวน" onClick={()=>quantity(item.clientId,-1)}>−</button><span>{item.quantity}</span><button type="button" aria-label="เพิ่มจำนวน" onClick={()=>quantity(item.clientId,1)}>+</button></div><button type="button" className="preorder-remove" onClick={()=>onChange(items.filter(x=>x.clientId!==item.clientId))}>นำออก</button></article>)}</div>}</div>;
}
