export const STATUS_LABELS={SUBMITTED:"รอฝ่ายจัดซื้อเปิดอ่าน",IN_REVIEW:"ฝ่ายจัดซื้อกำลังตรวจสอบ",NEEDS_INFO:"รอข้อมูลเพิ่มเติม",WAITING_CUSTOMER_DECISION:"แจ้งราคาแล้ว · รอคำตอบลูกค้า",PROCUREMENT_PENDING:"รอฝ่ายจัดซื้อดำเนินการ",ORDERED:"สั่งสินค้าแล้ว",RECEIVED_AT_HQ:"สำนักงานรับสินค้าแล้ว",IN_TRANSIT_TO_BRANCH:"อยู่ระหว่างส่งมาสาขา",ARRIVED_AT_BRANCH:"สินค้าถึงสาขาแล้ว",CUSTOMER_NOTIFIED:"แจ้งลูกค้าแล้ว",COMPLETED:"เสร็จสิ้น",CUSTOMER_DECLINED:"ลูกค้าไม่รับราคา",UNAVAILABLE:"ไม่สามารถจัดหาได้",CANCELLED:"ยกเลิก"};
export const INTENT_LABELS={PRICE_INQUIRY:"สอบถามราคา",ORDER_REQUEST:"สั่งสินค้า"};
export function statusLabel(value){return STATUS_LABELS[value]||"กำลังดำเนินการ";}
export function intentLabel(value){return INTENT_LABELS[value]||"คำขอสินค้า";}
export function clampQuantity(value){const number=Number(value);return Number.isFinite(number)&&number>0?Math.min(9999,Math.round(number*10000)/10000):1;}
export function mergeCatalogItem(items,suggestion){const unit=suggestion.unit||"";const index=items.findIndex(item=>item.itemKind==="CATALOG"&&Number(item.skuId)===Number(suggestion.sku_id)&&String(item.unit||"")===String(unit));if(index<0)return [...items,{clientId:crypto.randomUUID(),itemKind:"CATALOG",skuId:Number(suggestion.sku_id),productCode:suggestion.product_code,displayName:suggestion.display_name,genericName:suggestion.generic_name||"",barcode:suggestion.barcode||"",unit,quantity:1}];return items.map((item,i)=>i===index?{...item,quantity:clampQuantity(Number(item.quantity)+1)}:item);}
export function validateImages(files=[]){if(files.length>3)return "แนบรูปได้ไม่เกิน 3 รูป";for(const file of files){if(!["image/jpeg","image/png","image/webp"].includes(file.type))return "รองรับเฉพาะรูป JPEG, PNG หรือ WebP";if(file.size>5*1024*1024)return "แต่ละรูปต้องมีขนาดไม่เกิน 5 MB";}return "";}
export function validateDraft(draft,files=[]){const errors={};if(!draft.customerName?.trim())errors.customerName="กรุณากรอกชื่อลูกค้า";if(String(draft.customerPhone||"").replace(/\D/g,"").length<8)errors.customerPhone="กรุณากรอกเบอร์โทรให้ถูกต้อง";if(!Array.isArray(draft.items)||!draft.items.length)errors.items="กรุณาเพิ่มสินค้าอย่างน้อย 1 รายการ";const imageError=validateImages(files);if(imageError)errors.images=imageError;return errors;}
export function summarizeStatuses(items=[]){return {waitingAdmin:items.filter(x=>["SUBMITTED","IN_REVIEW","PROCUREMENT_PENDING","NEEDS_INFO"].includes(x.status)).length,waitingCustomer:items.filter(x=>x.status==="WAITING_CUSTOMER_DECISION").length,incoming:items.filter(x=>["ORDERED","RECEIVED_AT_HQ","IN_TRANSIT_TO_BRANCH"].includes(x.status)).length,ready:items.filter(x=>["ARRIVED_AT_BRANCH","CUSTOMER_NOTIFIED","COMPLETED"].includes(x.status)).length};}
export function adminActions(status){const modes=[];if(status==="SUBMITTED")modes.push(["start-review","เริ่มตรวจสอบ"]);if(["SUBMITTED","IN_REVIEW"].includes(status))modes.push(["quote","แจ้งราคา"]);if(["SUBMITTED","IN_REVIEW","PROCUREMENT_PENDING"].includes(status))modes.push(["request-info","ขอข้อมูลเพิ่ม"]);if(status==="PROCUREMENT_PENDING")modes.push(["ordered","บันทึกว่าสั่งแล้ว"]);if(["RECEIVED_AT_HQ","IN_TRANSIT_TO_BRANCH"].includes(status))modes.push(["confirm-arrival","ยืนยันว่าถึงสาขาแล้ว"]);if(["SUBMITTED","IN_REVIEW","NEEDS_INFO","WAITING_CUSTOMER_DECISION","PROCUREMENT_PENDING"].includes(status))modes.push(["unavailable","ไม่สามารถจัดหา"]);if(["COMPLETED","CUSTOMER_DECLINED","UNAVAILABLE","CANCELLED"].includes(status))modes.push(["reopen","เปิดเคสอีกครั้ง"]);return modes;}
export function staffActions(status){const modes=[];if(status==="WAITING_CUSTOMER_DECISION")modes.push(["decision","บันทึกคำตอบลูกค้า"]);if(status==="NEEDS_INFO")modes.push(["provide-info","ส่งข้อมูลเพิ่มเติมแล้ว"]);if(["RECEIVED_AT_HQ","IN_TRANSIT_TO_BRANCH"].includes(status))modes.push(["confirm-arrival","ยืนยันรับสินค้าที่สาขา"]);if(status==="ARRIVED_AT_BRANCH")modes.push(["customer-notified","บันทึกว่าแจ้งลูกค้าแล้ว"]);if(status==="CUSTOMER_NOTIFIED")modes.push(["complete","ปิดงานเสร็จสิ้น"]);if(["SUBMITTED","IN_REVIEW","NEEDS_INFO","PROCUREMENT_PENDING"].includes(status))modes.push(["cancel","ลูกค้ายกเลิก"]);return modes;}
export function receiptCoverage(items=[],evidence=[]){return items.map(item=>{const required=Number(item.confirmed_qty||item.requested_qty||0),allocated=evidence.filter(link=>link.evidence_type==="HQ_RECEIPT"&&Number(link.item_id)===Number(item.item_id)).reduce((sum,link)=>sum+Number(link.allocated_qty||0),0);return {itemId:item.item_id,required,allocated,complete:allocated>=required};});}
export function etaDescription(eta){if(!eta?.estimated_date)return "ยังไม่มีประมาณการ";const date=new Date(`${eta.estimated_date}T12:00:00+07:00`).toLocaleDateString("th-TH",{dateStyle:"medium"});return `ประมาณ ${date} · ${eta.is_override?"ฝ่ายจัดซื้อปรับวันที่พร้อมเหตุผล":"รอบส่งถัดไปหลังสำนักงานใหญ่รับสินค้า"}`;}
export function formatThaiDate(value){if(!value)return "-";const date=new Date(value);return Number.isNaN(date.getTime())?"-":date.toLocaleString("th-TH",{dateStyle:"short",timeStyle:"short"});}
