import {useEffect,useMemo,useRef,useState} from "react";import PreorderProductComposer from "./PreorderProductComposer.jsx";import {intentLabel,validateDraft,validateImages} from "./preorderHelpers.js";
const EMPTY={customerName:"",customerPhone:"",items:[],intent:"PRICE_INQUIRY",staffNote:""};
export default function PreorderCreateDialog({api,onClose,onCreated}){const [draft,setDraft]=useState(EMPTY),[files,setFiles]=useState([]),[step,setStep]=useState(1),[error,setError]=useState(""),[submitting,setSubmitting]=useState(false);const dialogRef=useRef(null),closeRef=useRef(null);const previews=useMemo(()=>files.map(file=>({file,url:URL.createObjectURL(file)})),[files]);
 useEffect(()=>()=>previews.forEach(x=>URL.revokeObjectURL(x.url)),[previews]);
 useEffect(()=>{const previous=document.activeElement;const priorOverflow=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();function key(event){if(event.key==="Escape")onClose();if(event.key==="Tab"){const nodes=[...dialogRef.current.querySelectorAll('button,input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=priorOverflow;previous?.focus?.();};},[onClose]);
 async function addFiles(event){const picked=[...event.target.files];event.target.value="";const next=[...files,...picked].slice(0,3);const message=validateImages(next);if(message){setError(message);return;}const frozen=await Promise.all(next.map(async item=>{if(!(item instanceof File))return item;const buffer=await item.arrayBuffer();const blob=new Blob([buffer],{type:item.type});blob.name=item.name;blob.lastModified=item.lastModified;return blob;}));setFiles(frozen);setError("");}
 function canContinue(){if(step===1)return draft.customerName.trim()&&String(draft.customerPhone).replace(/\D/g,"").length>=8;if(step===2)return draft.items.length>0;return true;}
 async function submit(){const errors=validateDraft(draft,files);if(Object.keys(errors).length){setError(Object.values(errors)[0]);return;}setSubmitting(true);setError("");try{const form=new FormData();form.set("payload",JSON.stringify({idempotencyKey:crypto.randomUUID(),customerName:draft.customerName,customerPhone:draft.customerPhone,intent:draft.intent,staffNote:draft.staffNote,items:draft.items.map(({clientId,...item})=>item)}));files.forEach(file=>form.append("images",file,file.name));const created=await api.createCase(form);await onCreated(created);}catch(ex){setError(ex.message||"ส่งคำขอไม่สำเร็จ");}finally{setSubmitting(false);}}
 return <div className="preorder-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section ref={dialogRef} className="preorder-dialog" role="dialog" aria-modal="true" aria-labelledby="preorder-dialog-title"><header><div><span>ขั้นตอน {step} จาก 5</span><h3 id="preorder-dialog-title">สร้างรายการพรีออเดอร์</h3></div><button ref={closeRef} type="button" className="preorder-close" aria-label="ปิดหน้าต่าง" onClick={onClose}>×</button></header><ol className="preorder-steps" aria-label="ขั้นตอนสร้างรายการ">{["ลูกค้า","สินค้า","รูปประกอบ","ประเภทคำขอ","ตรวจสอบ"].map((label,index)=><li key={label} className={step===index+1?"active":step>index+1?"done":""}><span>{index+1}</span>{label}</li>)}</ol>{error&&<div className="preorder-error" role="alert">{error}</div>}<div className="preorder-step-body">
 {step===1&&<fieldset><legend>ข้อมูลลูกค้า</legend><label>ชื่อลูกค้า<input autoComplete="name" value={draft.customerName} onChange={e=>setDraft({...draft,customerName:e.target.value})}/></label><label>เบอร์โทร<input inputMode="tel" autoComplete="tel" value={draft.customerPhone} onChange={e=>setDraft({...draft,customerPhone:e.target.value})}/></label><p className="preorder-hint">ข้อมูลเต็มจะแสดงเฉพาะในรายละเอียดที่ได้รับอนุญาต</p></fieldset>}
 {step===2&&<fieldset><legend>สินค้าที่ลูกค้าต้องการ</legend><PreorderProductComposer api={api} items={draft.items} onChange={items=>setDraft({...draft,items})}/></fieldset>}
 {step===3&&<fieldset><legend>รูปประกอบ</legend><p className="preorder-hint">ไม่บังคับ · สูงสุด 3 รูป เฉพาะ JPEG, PNG หรือ WebP รูปละไม่เกิน 5 MB</p><label className="preorder-file-button">เลือกรูป<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={addFiles}/></label><strong>{files.length}/3 รูป</strong>{previews.length>0&&<div className="preorder-previews">{previews.map(({file,url},index)=><figure key={`${file.name}-${file.lastModified}`}><img src={url} alt={`รูปประกอบ ${index+1}`}/><figcaption>{file.name}</figcaption><button type="button" onClick={()=>setFiles(files.filter((_,i)=>i!==index))}>นำรูปออก</button></figure>)}</div>}</fieldset>}
 {step===4&&<fieldset><legend>ประเภทคำขอ</legend><label>ลูกค้าต้องการ<select value={draft.intent} onChange={e=>setDraft({...draft,intent:e.target.value})}><option value="PRICE_INQUIRY">สอบถามราคา</option><option value="ORDER_REQUEST">สั่งสินค้า</option></select></label><label>หมายเหตุถึงฝ่ายจัดซื้อ<textarea value={draft.staffNote} onChange={e=>setDraft({...draft,staffNote:e.target.value})} maxLength="2000" placeholder="ข้อมูลเพิ่มเติม (ถ้ามี)"/></label></fieldset>}
 {step===5&&<div className="preorder-review"><h4>ตรวจสอบก่อนส่ง</h4><dl><div><dt>ลูกค้า</dt><dd>{draft.customerName} · {draft.customerPhone}</dd></div><div><dt>ประเภท</dt><dd>{intentLabel(draft.intent)}</dd></div><div><dt>สินค้า</dt><dd>{draft.items.length} รายการ</dd></div><div><dt>รูป</dt><dd>{files.length}/3 รูป</dd></div></dl>{draft.items.map(item=><article key={item.clientId}><strong>{item.itemKind==="CATALOG"?item.displayName:"สินค้านอกระบบ"}</strong><span>{item.itemKind==="CATALOG"?item.productCode:item.description}</span><span>จำนวน {item.quantity}</span></article>)}</div>}
 </div><footer className="preorder-actions"><button type="button" onClick={step===1?onClose:()=>setStep(step-1)}>{step===1?"ยกเลิก":"ย้อนกลับ"}</button>{step<5?<button type="button" className="primary" disabled={!canContinue()} onClick={()=>{setError("");setStep(step+1);}}>ถัดไป</button>:<button type="button" className="primary" disabled={submitting} onClick={submit}>{submitting?"กำลังส่ง…":"ยืนยันและส่ง"}</button>}</footer></section></div>;
}
