import {useCallback,useEffect,useRef,useState} from "react";
import {formatThaiDate,intentLabel,statusLabel} from "./preorderHelpers.js";
import PreorderTimeline from "./PreorderTimeline.jsx";
import PreorderActions from "./PreorderActions.jsx";
import PreorderSkuMatcher from "./PreorderSkuMatcher.jsx";
import PreorderReceiptEvidence from "./PreorderReceiptEvidence.jsx";
import PreorderTransferEvidence from "./PreorderTransferEvidence.jsx";

export default function PreorderDetailDrawer({publicId,api,isAdmin,onClose,onRead,onChanged}){
  const [detail,setDetail]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);const closeRef=useRef(null);
  const load=useCallback(async(mark=true)=>{setLoading(true);setError("");try{if(mark){await api.markRead(publicId);onRead?.();}setDetail(await api.getCase(publicId));}catch(ex){setError(ex.message||"โหลดรายละเอียดไม่สำเร็จ");}finally{setLoading(false);}},[api,publicId,onRead]);
  useEffect(()=>{load(true);},[load]);useEffect(()=>{const previous=document.activeElement,priorOverflow=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const key=event=>{if(event.key==="Escape")onClose();};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=priorOverflow;previous?.focus?.();};},[onClose]);
  async function refresh(){await load(false);onChanged?.();onRead?.();}async function openAttachment(id){try{const data=await api.downloadUrl(id);window.open(data.url,"_blank","noopener,noreferrer");}catch(ex){setError(ex.message||"เปิดรูปไม่สำเร็จ");}}
  return <div className="preorder-drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><aside className="preorder-drawer" role="dialog" aria-modal="true" aria-labelledby="preorder-detail-title"><header><div><span>รายละเอียดคำขอ</span><h3 id="preorder-detail-title">{publicId}</h3></div><button ref={closeRef} type="button" aria-label="ปิดรายละเอียด" onClick={onClose}>×</button></header>{loading&&<div className="preorder-loading">กำลังโหลดรายละเอียด…</div>}{error&&<div className="preorder-error" role="alert">{error}</div>}{detail&&<div className="preorder-detail-grid"><section>
    <div className="preorder-detail-status"><span className={`preorder-status status-${String(detail.status).toLowerCase()}`}>{statusLabel(detail.status)}</span><small>{intentLabel(detail.intent)}</small></div>
    <dl className="preorder-detail-list"><div><dt>ลูกค้า</dt><dd>{detail.customer_name}</dd></div><div><dt>เบอร์โทร</dt><dd>{detail.customer_phone}</dd></div><div><dt>สาขา</dt><dd>{detail.branch_code}</dd></div><div><dt>สร้างเมื่อ</dt><dd>{formatThaiDate(detail.created_at)}</dd></div><div><dt>ฝ่ายจัดซื้อเปิดอ่าน</dt><dd>{detail.first_admin_viewed_at?formatThaiDate(detail.first_admin_viewed_at):"ยังไม่เปิดอ่าน"}</dd></div></dl>
    <h4>สินค้า</h4><div className="preorder-detail-items">{detail.items?.map(item=><article key={item.item_id}><strong>{item.item_kind==="CATALOG"?item.display_name_snapshot:"สินค้านอกระบบ"}</strong><p>{item.item_kind==="CATALOG"?[item.product_code_snapshot,item.barcode_snapshot,item.unit_snapshot].filter(Boolean).join(" · "):item.original_description}</p><span>จำนวน {item.confirmed_qty||item.requested_qty}</span></article>)}</div>
    {detail.quotes?.length>0&&<div className="preorder-quote-history"><h4>ใบเสนอราคา</h4>{detail.quotes.map(quote=><article key={quote.quote_id}><strong>ฉบับที่ {quote.quote_version}</strong>{quote.lines?.map(line=><p key={line.quoteLineId}>จำนวน {line.offeredQty} · {Number(line.unitPrice).toLocaleString("th-TH",{style:"currency",currency:"THB"})}</p>)}{quote.public_note&&<small>{quote.public_note}</small>}{isAdmin&&quote.admin_internal_note&&<small>ภายใน: {quote.admin_internal_note}</small>}</article>)}</div>}
    {detail.procurementOutcomes?.length>0&&<div><h4>ผลการจัดซื้อ</h4>{detail.procurementOutcomes.map(outcome=><p key={outcome.outcome_id}>{outcome.outcome_type==="ORDERED"?"สั่งสินค้าแล้ว":`ไม่สามารถจัดหา · ${outcome.reason_code}`}{outcome.public_note?` · ${outcome.public_note}`:""}{isAdmin&&outcome.admin_internal_note?` · ภายใน: ${outcome.admin_internal_note}`:""}</p>)}</div>}
    {detail.staff_note&&<><h4>หมายเหตุ</h4><p>{detail.staff_note}</p></>}{detail.attachments?.length>0&&<><h4>รูปประกอบ</h4><div className="preorder-attachment-list">{detail.attachments.map((item,index)=><button type="button" key={item.attachment_public_id} onClick={()=>openAttachment(item.attachment_public_id)}>เปิดรูป {index+1} · {(Number(item.size_bytes)/1024/1024).toFixed(1)} MB</button>)}</div></>}
    {["ORDERED","RECEIVED_AT_HQ","IN_TRANSIT_TO_BRANCH"].includes(detail.status)&&<PreorderReceiptEvidence detail={detail} isAdmin={isAdmin} api={api} onUpdated={refresh}/>} {["RECEIVED_AT_HQ","IN_TRANSIT_TO_BRANCH","ARRIVED_AT_BRANCH"].includes(detail.status)&&<PreorderTransferEvidence detail={detail} isAdmin={isAdmin} api={api} onUpdated={refresh}/>} {isAdmin&&<PreorderSkuMatcher detail={detail} api={api} onUpdated={refresh}/>}<PreorderActions detail={detail} isAdmin={isAdmin} api={api} onUpdated={refresh}/>
  </section><section><h4>กิจกรรม</h4><PreorderTimeline entries={detail.timeline}/></section></div>}</aside></div>;
}
