import {useMemo,useState} from "react";
import {etaDescription,receiptCoverage} from "./preorderHelpers.js";

export default function PreorderReceiptEvidence({detail,isAdmin,api,onUpdated}){const coverage=useMemo(()=>receiptCoverage(detail.items,detail.evidence),[detail.items,detail.evidence]);const [itemId,setItemId]=useState(detail.items?.[0]?.item_id||""),[candidates,setCandidates]=useState([]),[selected,setSelected]=useState(null),[allocatedQty,setAllocatedQty]=useState(""),[sourceAllocatedQty,setSourceAllocatedQty]=useState(""),[note,setNote]=useState(""),[unlinkReason,setUnlinkReason]=useState(""),[etaDate,setEtaDate]=useState(""),[etaReason,setEtaReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const activeCoverage=coverage.find(x=>Number(x.itemId)===Number(itemId));
 async function loadCandidates(){setBusy(true);setError("");try{const data=await api.receiptCandidates(detail.public_id,itemId);setCandidates(data.items||[]);setSelected(null);}catch(ex){setError(ex.message);}finally{setBusy(false);}}
 function choose(row){const qty=Math.min(Number(row.availableSourceQty),Math.max(0,(activeCoverage?.required||0)-(activeCoverage?.allocated||0)));setSelected(row);setAllocatedQty(String(qty||""));setSourceAllocatedQty(String(qty||""));setNote("");}
 async function link(){setBusy(true);setError("");try{await api.linkReceipt(detail.public_id,itemId,{expectedVersion:detail.version,sourceBranch:selected.branch_code,docNo:selected.doc_no,seqNo:selected.seq_no,allocatedQty,sourceAllocatedQty,allocationNote:note});await onUpdated();setCandidates([]);setSelected(null);}catch(ex){setError(ex.status===409?"ข้อมูลหรือจำนวนคงเหลือเปลี่ยนแปลง กรุณาโหลดใหม่":ex.message);}finally{setBusy(false);}}
 async function unlink(linkId){if(!unlinkReason.trim())return;setBusy(true);setError("");try{await api.unlinkReceipt(detail.public_id,linkId,{expectedVersion:detail.version,reason:unlinkReason});setUnlinkReason("");await onUpdated();}catch(ex){setError(ex.message);}finally{setBusy(false);}}
 async function override(){setBusy(true);setError("");try{await api.overrideEta(detail.public_id,{expectedVersion:detail.version,estimatedDate:etaDate,reason:etaReason});setEtaDate("");setEtaReason("");await onUpdated();}catch(ex){setError(ex.message);}finally{setBusy(false);}}
 return <div className="preorder-receipt-evidence"><h4>การรับสินค้าที่สำนักงานใหญ่</h4><div className="preorder-coverage">{coverage.map(line=>{const item=detail.items.find(x=>Number(x.item_id)===Number(line.itemId));return <div key={line.itemId}><span>{item?.display_name_snapshot||item?.original_description}</span><strong className={line.complete?"complete":""}>{line.allocated} / {line.required} {item?.unit_snapshot||""}</strong></div>;})}</div><p className="preorder-eta"><strong>ETA:</strong> {etaDescription(detail.eta)}</p>{detail.eta?.source_evidence_date&&<small>อ้างอิงหลักฐานรับเข้าสำนักงานใหญ่วันที่ {detail.eta.source_evidence_date}</small>}
 {detail.evidence?.length>0&&<div className="preorder-linked-evidence">{detail.evidence.filter(x=>x.evidence_type==="HQ_RECEIPT").map(link=><article key={link.evidence_link_id}><div><strong>{link.snapshot_json?.productCode||"หลักฐานรับเข้า"}</strong><span>จัดสรร {link.allocated_qty} {link.target_unit||link.unit||""} · เอกสารวันที่ {link.snapshot_json?.docDate||"-"}</span><small>ซิงก์ล่าสุด {link.source_synced_at?new Date(link.source_synced_at).toLocaleString("th-TH"):"ไม่ทราบเวลา"}</small></div>{isAdmin&&<button type="button" disabled={busy||!unlinkReason.trim()} onClick={()=>unlink(link.evidence_link_id)}>ยกเลิกการผูก</button>}</article>)}</div>}
 {isAdmin&&["ORDERED","RECEIVED_AT_HQ"].includes(detail.status)&&<div className="preorder-receipt-admin"><label>สินค้า<select value={itemId} onChange={e=>{setItemId(e.target.value);setCandidates([]);setSelected(null);}}>{detail.items.map(item=><option key={item.item_id} value={item.item_id}>{item.display_name_snapshot||item.original_description}</option>)}</select></label><button type="button" disabled={busy} onClick={loadCandidates}>ค้นหาใบรับเข้ารหัสตรงกัน</button>{candidates.length>0&&<div className="preorder-receipt-candidates">{candidates.map(row=><button type="button" key={row.sourceKey} disabled={row.availableSourceQty<=0} onClick={()=>choose(row)}><strong>{row.doc_no} · {row.doc_date}</strong><span>{row.product_code} · คงเหลือ {row.availableSourceQty} {row.unit_code||row.unit_name||""}</span><small>ซิงก์ {new Date(row.source_synced_at).toLocaleString("th-TH")}{row.unitMatches?"":" · หน่วยไม่ตรง"}</small></button>)}</div>}{selected&&<div className="preorder-allocation-form"><label>จำนวนที่ครอบคลุมในเคส<input type="number" min="0.0001" step="any" value={allocatedQty} onChange={e=>setAllocatedQty(e.target.value)}/></label><label>จำนวนที่ใช้จากเอกสารต้นทาง<input type="number" min="0.0001" step="any" value={sourceAllocatedQty} onChange={e=>setSourceAllocatedQty(e.target.value)}/></label>{!selected.unitMatches&&<label>เหตุผลและอัตราเทียบหน่วย<textarea value={note} onChange={e=>setNote(e.target.value)}/></label>}<button className="primary" type="button" disabled={busy||!allocatedQty||!sourceAllocatedQty||(!selected.unitMatches&&!note.trim())} onClick={link}>ยืนยันการจัดสรร</button></div>}<label>เหตุผลเมื่อยกเลิกการผูก<input value={unlinkReason} onChange={e=>setUnlinkReason(e.target.value)} placeholder="ต้องระบุก่อนกดยกเลิก"/></label></div>}
 {isAdmin&&["RECEIVED_AT_HQ","IN_TRANSIT_TO_BRANCH"].includes(detail.status)&&<div className="preorder-eta-override"><h4>ปรับ ETA</h4><label>วันที่โดยประมาณ<input type="date" value={etaDate} onChange={e=>setEtaDate(e.target.value)}/></label><label>เหตุผล<textarea value={etaReason} onChange={e=>setEtaReason(e.target.value)}/></label><button type="button" disabled={busy||!etaDate||!etaReason.trim()} onClick={override}>บันทึกการปรับ ETA</button></div>}{error&&<div className="preorder-error" role="alert">{error}</div>}</div>;
}
