CREATE TABLE IF NOT EXISTS ada_transfer_headers (
  doc_no TEXT NOT NULL,
  doc_type TEXT NOT NULL,
  branch_code TEXT NOT NULL,
  branch_code_to TEXT,
  warehouse_code TEXT,
  warehouse_code_to TEXT,
  doc_date DATE,
  tnf_date DATE,
  transfer_type TEXT,
  total NUMERIC(14, 4),
  vat NUMERIC(14, 4),
  grand NUMERIC(14, 4),
  dept_code TEXT,
  created_by TEXT,
  approved_by TEXT,
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (doc_no, doc_type, branch_code)
);

CREATE TABLE IF NOT EXISTS ada_transfer_lines (
  doc_no TEXT NOT NULL,
  doc_type TEXT NOT NULL,
  branch_code TEXT NOT NULL,
  branch_code_to TEXT,
  line_no INTEGER NOT NULL,
  product_code TEXT NOT NULL,
  unit_code TEXT,
  unit_name TEXT,
  qty NUMERIC(14, 4),
  qty_base NUMERIC(14, 4),
  stock_factor NUMERIC(14, 4),
  cost NUMERIC(14, 4),
  cost_in NUMERIC(14, 4),
  net NUMERIC(14, 4),
  vat NUMERIC(14, 4),
  warehouse_code TEXT,
  warehouse_code_to TEXT,
  doc_date DATE,
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (doc_no, doc_type, branch_code, line_no, product_code)
);
